import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
registerHooks({ resolve(specifier, context, nextResolve) {
  try { return nextResolve(specifier, context); }
  catch (error) { if (error.code === 'ERR_MODULE_NOT_FOUND' && specifier.startsWith('.') && !/\.[a-z]+$/i.test(specifier)) return nextResolve(specifier + '.ts', context); throw error; }
}});
const { EMPTY_PORTFOLIO, positionCost, positionValue, validPortfolio } = await import('../lib/portfolio.ts');
const { quoteRequest, suggestedLookup, validQuoteRequest, usableQuote, applyMarketQuotes } = await import('../lib/market.ts');
const { getMarketQuotes } = await import('../lib/market-server.ts');
const now = Date.now(), stamp = Math.floor(now / 1000), date = new Date(now).toISOString();
const p = { id: 'position', accountId: 'account', symbol: 'VFV', name: 'Test ETF', kind: 'FNB', quantity: 10, cost: 90, price: 100, currency: 'CAD', bookValue: 800, marketValue: 750, valuationCurrency: 'USD' };
const request = quoteRequest(p, 'VFV.TO');
const q = { ...request, price: 150, source: 'Yahoo Finance', name: 'Test ETF', quotedAt: date, fetchedAt: date };
const state = { ...EMPTY_PORTFOLIO, usdCad: 1.4, accounts: [{ id: 'account', name: 'CELI', provider: 'Wealthsimple', currency: 'CAD' }], positions: [p] };
assert(validQuoteRequest(request));
assert(!validQuoteRequest({ ...request, lookup: 'https://untrusted.example' }));
assert(!validQuoteRequest({ ...request, currency: 'EUR' }));
assert(!validQuoteRequest({ ...request, key: 'another' }));
assert.equal(suggestedLookup(p), 'VFV.TO');
assert.equal(suggestedLookup({ ...p, symbol: 'BIP.UN' }), 'BIP-UN.TO');
assert.equal(suggestedLookup({ ...p, symbol: 'ABC.V' }), 'ABC.V');
assert.equal(suggestedLookup({ ...p, symbol: 'BTC', kind: 'Crypto' }), 'bitcoin');
assert.equal(suggestedLookup({ ...p, symbol: 'UNKNOWN', kind: 'Crypto' }), '');
assert(!usableQuote({ ...q, price: 0 }, request, now));
assert(!usableQuote({ ...q, price: NaN }, request, now));
assert(!usableQuote({ ...q, currency: 'USD' }, request, now));
assert(!usableQuote({ ...q, quotedAt: new Date(now - 8 * 86400000).toISOString() }, request, now));
assert(!usableQuote({ ...q, quotedAt: new Date(now + 600000).toISOString() }, request, now));
const applied = applyMarketQuotes(state, [{ before: p, request, quote: q }], now);
assert.equal(applied.updated, 1);
assert(validPortfolio(applied.state));
assert.equal(applied.state.positions[0].quantity, p.quantity);
assert.equal(positionValue(applied.state.positions[0], 1.4), 1500);
assert.equal(positionCost(applied.state.positions[0], 1.4), positionCost(p, 1.4), 'Preserve statement cost in its original currency');
assert.equal(applied.state.positions[0].marketValue, undefined);
assert.equal(applied.state.positions[0].bookValue, 800);
assert.equal(applied.state.positions[0].market.source, 'Yahoo Finance');
const edited = { ...state, positions: [{ ...p, quantity: 20 }] };
assert.equal(applyMarketQuotes(edited, [{ before: p, request, quote: q }], now).updated, 0, 'Do not overwrite an edited holding');
assert.equal(applyMarketQuotes({ ...state, positions: [] }, [{ before: p, request, quote: q }], now).updated, 0);
const futurePosition = { ...p, asOf: new Date(now + 86400000).toISOString().slice(0, 10) };
assert.equal(applyMarketQuotes({ ...state, positions: [futurePosition] }, [{ before: futurePosition, request, quote: q }], now).updated, 0, 'Never replace newer valuations');
const btc = quoteRequest({ ...p, kind: 'Crypto', symbol: 'BTC' }, 'bitcoin');
const eth = quoteRequest({ ...p, kind: 'Crypto', symbol: 'ETH', currency: 'USD' }, 'ethereum');
const wrongCurrency = quoteRequest({ ...p, symbol: 'AAPL' }, 'AAPL');
let calls = 0;
const fixture = async url => {
  calls++;
  if (url.hostname === 'api.coingecko.com') {
    assert.equal(url.searchParams.get('include_last_updated_at'), 'true');
    return Response.json({ bitcoin: { cad: 100000, last_updated_at: stamp }, ethereum: { usd: 2000, last_updated_at: stamp } });
  }
  return Response.json({ chart: { result: [{ meta: { symbol: url.pathname.endsWith('AAPL') ? 'AAPL' : 'VFV.TO', currency: url.pathname.endsWith('AAPL') ? 'USD' : 'CAD', instrumentType: 'ETF', regularMarketPrice: 150, regularMarketTime: stamp, longName: 'Fixture' } }] } });
};
const result = await getMarketQuotes([request, request, btc, eth, wrongCurrency], fixture, now, false);
assert.equal(calls, 3, 'Deduplicate equities and batch crypto IDs');
assert.equal(Object.keys(result.quotes).length, 3);
assert(result.errors[wrongCurrency.key].includes('Devise'));
assert.equal(result.quotes[btc.key].price, 100000);
assert.equal(result.quotes[eth.key].currency, 'USD');
const unavailable = await getMarketQuotes([request, btc], async () => new Response('', { status: 429 }), now, false);
assert.equal(Object.keys(unavailable.quotes).length, 0);
assert.equal(Object.keys(unavailable.errors).length, 2);
const old = await getMarketQuotes([btc], async () => Response.json({ bitcoin: { cad: 100000, last_updated_at: stamp - 3600 } }), now, false);
assert.equal(Object.keys(old.quotes).length, 0);
const empty = await getMarketQuotes([request], async () => Response.json({ chart: { result: [{ meta: { symbol: 'VFV.TO', currency: 'CAD', instrumentType: 'ETF', regularMarketPrice: 150 } }] } }), now, false);
assert.equal(Object.keys(empty.quotes).length, 0, 'Never invent a missing quote timestamp');
console.log('Market data checks passed: source parsing, currencies, timestamps, batching, partial failures, cost preservation and concurrent edits.');

const { totals, withSnapshot } = await import('../lib/portfolio.ts');
const { historyForPeriod, snapshotTime } = await import('../lib/history.ts');
assert.equal(applied.state.snapshots.length, 2, 'First refresh records the known before/after values');
assert.equal(applied.state.snapshots[0].value, positionValue(p, state.usdCad));
assert.equal(applied.state.snapshots.at(-1).value, totals(applied.state).value);
assert.equal(applied.state.snapshots.at(-1).cost, totals(applied.state).cost);
assert.equal(applied.state.snapshots.at(-1).capturedAt, date);
assert(validPortfolio(JSON.parse(JSON.stringify(applied.state))), 'Timestamped history survives backup/restore');
const beforeAgain = applied.state.positions[0];
const nextDate = new Date(now + 60000).toISOString();
const updatedAgain = applyMarketQuotes(applied.state, [{ before: beforeAgain, request, quote: { ...q, price: 160, quotedAt: nextDate, fetchedAt: nextDate } }], now + 60000);
assert.equal(updatedAgain.state.snapshots.length, 3, 'Same-day updates append instead of replacing');
assert.equal(updatedAgain.state.snapshots.at(-1).value, 1600);
assert.equal(updatedAgain.state.snapshots[1].value, 1500, 'Earlier same-day value is retained');
assert.equal(historyForPeriod(updatedAgain.state.snapshots, '1J', now + 60000).length, 3);
assert.deepEqual(applyMarketQuotes(updatedAgain.state, []).state.snapshots, updatedAgain.state.snapshots, 'No applied quotes means no history change');
const mismatch = applyMarketQuotes(updatedAgain.state, [{ before: updatedAgain.state.positions[0], request, quote: { ...q, currency: 'USD' } }], now);
assert.equal(mismatch.updated, 0);
assert.deepEqual(mismatch.state.snapshots, updatedAgain.state.snapshots, 'Rejected quotes do not add points');
const legacy = { date: '2020-01-01', value: 500, cost: 400 };
assert(validPortfolio({ ...state, snapshots: [legacy] }), 'Legacy date-only histories remain valid');
assert(!validPortfolio({ ...state, snapshots: [{ ...legacy, capturedAt: 'invalid' }] }));
assert(!validPortfolio({ ...state, snapshots: [{ ...legacy, capturedAt: '2020-01-02T00:00:00.000Z' }] }));
const mixed = [updatedAgain.state.snapshots.at(-1), legacy, applied.state.snapshots[0]];
assert.equal(historyForPeriod(mixed, 'Tout', now + 60000)[0], legacy);
assert.equal(historyForPeriod(mixed, '1J', now + 60000).length, 2);
assert.equal(snapshotTime(legacy), Date.parse('2020-01-01T00:00:00.000Z'));
const one = withSnapshot(state, new Date(now));
assert.equal(historyForPeriod(one.snapshots, '1J', now).length, 1, 'A single point remains available for plotting');
assert.equal(withSnapshot(one, new Date(now)).snapshots.length, 1, 'Do not duplicate an identical capture in the same instant');
const many = { ...state, snapshots: Array.from({ length: 5000 }, (_, i) => ({ date: '2020-01-01', value: i, cost: i })) };
const capped = withSnapshot(many, new Date(now));
assert.equal(capped.snapshots.length, 5000);
assert.equal(capped.snapshots.at(-1).value, totals(state).value);
console.log('History checks passed: immediate curve value, same-day refreshes, legacy backups, time filters, single-point data and failed refreshes.');
